### ISSUE TITLE
Tests are flaky

### ISSUE THREAD

**Issue by morgante** [terraform-google-modules/terraform-google-scheduled-function#39]
When executing tests, it looks like functions fail to converge:

```
       module.pubsub_scheduled_example.module.pubsub_scheduled_example.module.main.google_cloudfunctions_function.main: Still creating... [10s elapsed]
       
       Error: Error waiting for Creating CloudFunctions Function: Error code 3, message: Failed to retrieve function source code
       
         on .terraform/modules/pubsub_scheduled_example.pubsub_scheduled_example.main/terraform-google-event-function-1.2.0/main.tf line 68, in resource "google_cloudfunctions_function" "main":
         68: resource "google_cloudfunctions_function" "main" {
```

**Comment by bharathkkb** [comment]
Did some digging, CF API response does not explicitly say what was the error but I believe it was due to nodejs6 being [deprecated](https://cloud.google.com/functions/docs/concepts/nodejs-6-runtime). 
> After 2020-08-05, function deployments that use Node.js 6 will be blocked. 

Set default to nodejs10 in https://github.com/terraform-google-modules/terraform-google-scheduled-function/pull/42
